name: campus_safar
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


#---------PACKAGES---------#
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.2.0
  persistent_bottom_nav_bar: ^5.0.2
  google_nav_bar: ^5.0.6
  see_more: ^0.0.1


  #--Firebase----#
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.4
  connection_notifier: ^2.0.1
  shared_preferences: ^2.0.11
  email_validator: ^2.1.17
  shared_preferences_android: ^2.1.0
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  firebase_storage: ^11.5.4
  crypto: ^3.0.3

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.2.0
  flutter_animate: ^4.3.0
  provider: ^6.1.1
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  file_previewer: ^0.1.0
  dio: ^5.4.2+1
  open_filex: 4.4.0
  excel: 4.0.2
  permission_handler: ^11.2.1
  auto_size_text: ^3.0.0
  scroll_snap_list: ^0.9.1
  url_launcher: ^6.2.5
  webview_flutter: ^3.0.1
  csv: ^6.0.0
  path_provider: ^2.1.2
  carousel_slider: ^4.2.1
  flutter_face_api: ^6.1.1
  google_mlkit_face_detection: ^0.9.0
  audioplayers: ^6.0.0
  # QR Packages
  qr_scanner: ^0.0.2-259.9.beta
  qr_flutter: ^4.1.0
  qrscan: ^0.3.3
  country_code_picker: ^3.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_tawk: ^0.1.0




  #----------./ PACKAGES END ------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  #-----------LOCAL ASSETS----------#
  assets:
    - assets/logos/company_logos/amazon.png
    - assets/logos/company_logos/google.png
    - assets/logos/company_logos/microsoft.png
    - assets/logos/company_logos/tcs.png
    - assets/logos/company_logos/.
    - assets/logos/app_logo/.
    - assets/icons/app_icon.png
    - assets/images/on_boarding_images/.
    - assets/images/profile_images/.
    - assets/images/login_signup_images/.
    - assets/images/.
    - assets/.


  #----------LOCAL FONTS---------#
#  fonts:
#    - family:
#      fonts:
#        - asset:
#        - weight:
#        - style:

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
