// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYtU-BlqBSAhQPeD7YJg9Q4uI0BuVOs0',
    appId: '1:534958785261:web:6a4f9d212686e2773c02e4',
    messagingSenderId: '534958785261',
    projectId: 'smartcareerconnect-c8269',
    authDomain: 'smartcareerconnect-c8269.firebaseapp.com',
    databaseURL: 'https://smartcareerconnect-c8269-default-rtdb.firebaseio.com',
    storageBucket: 'smartcareerconnect-c8269.appspot.com',
    measurementId: 'G-N788MT2QGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeITmSjr7BRx_cztt29oDM-YxCaBwT_k',
    appId: '1:534958785261:android:3ae5873f1db97c093c02e4',
    messagingSenderId: '534958785261',
    projectId: 'smartcareerconnect-c8269',
    databaseURL: 'https://smartcareerconnect-c8269-default-rtdb.firebaseio.com',
    storageBucket: 'smartcareerconnect-c8269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDW6pRHfFEUZnzvVJ3UFbLmz1ZYSnmgc',
    appId: '1:534958785261:ios:e0a2d22ccf55cee83c02e4',
    messagingSenderId: '534958785261',
    projectId: 'smartcareerconnect-c8269',
    databaseURL: 'https://smartcareerconnect-c8269-default-rtdb.firebaseio.com',
    storageBucket: 'smartcareerconnect-c8269.appspot.com',
    iosBundleId: 'com.scc.campussafar.csafar',
  );
}
